name: gest_clinique
description: Gestion de clinique.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: any
  fast_cached_network_image: any
  image_picker: any
  url_launcher: any
  google_fonts: any
  shared_preferences: any
  lottie: any
  intl: any
  mime: any
  launch_review: any
  mailer: any
  http: any
  image: any
  path_provider: any
  package_info_plus: any
  awesome_dialog: any
  table_calendar: any
  fl_chart: any

  #photo_view: any
  #jiffy: any
  #font_awesome_flutter: any
  #awesome_notifications: any
  #progress_indicators: any
  #quiver: any
  ##step_progress_indicator: any
  #grouped_list: any
  #file_picker: any
  #crop_your_image: any
  #blinking_text: any
  #scrollable_list_tabview: any
  #drift: any
  #drift_dev: any
  #sqlite3: any
  #sqlite3_flutter_libs: any
  #path: any
  #video_thumbnail: any
  #appinio_video_player: any
  #uni_links: any
  #fluttertoast: any
  #animated_text_kit: any
  #rename: any
  #provider: any
  #flutter_localization: any
  #open_file: any
  #syncfusion_flutter_pdf: any
  #app_settings: any
  #permission_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  flutter_launcher_icons: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/

  fonts:
    - family: Arabtype
      fonts:
        - asset: assets/fonts/arabtype.ttf

    - family: Traditional
      fonts:
        - asset: assets/fonts/trado.ttf
        - asset: assets/fonts/tradbdo.ttf
          weight: 700
